/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <jni.h>
#include <stdlib.h>
#include <string.h>
#include <android/log.h>

#define LOG_TAG "AegisSingBox"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

static void log_info(const char* msg) {
    __android_log_print(ANDROID_LOG_INFO, LOG_TAG, "%s", msg);
}

static void log_error(const char* msg) {
    __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, "%s", msg);
}

static const char* getStringUTF(JNIEnv *env, jstring str) {
    return (*env)->GetStringUTFChars(env, str, NULL);
}

static jstring newStringUTF(JNIEnv *env, const char *bytes) {
    return (*env)->NewStringUTF(env, bytes);
}

static jlongArray newLongArray(JNIEnv *env, jsize len) {
    return (*env)->NewLongArray(env, len);
}

static void setLongArrayRegion(JNIEnv *env, jlongArray array, jsize start, jsize len, const jlong *buf) {
    (*env)->SetLongArrayRegion(env, array, start, len, buf);
}

static jmethodID getMethodID(JNIEnv *env, jclass clazz, const char *name, const char *sig) {
    return (*env)->GetMethodID(env, clazz, name, sig);
}

static jboolean callBooleanMethod(JNIEnv *env, jobject obj, jmethodID methodID, jint arg) {
    return (*env)->CallBooleanMethod(env, obj, methodID, arg);
}

static void deleteGlobalRef(JNIEnv *env, jobject obj) {
    (*env)->DeleteGlobalRef(env, obj);
}

static jobject newGlobalRef(JNIEnv *env, jobject obj) {
    return (*env)->NewGlobalRef(env, obj);
}

static jclass getObjectClass(JNIEnv *env, jobject obj) {
    return (*env)->GetObjectClass(env, obj);
}

static JavaVM* getJavaVM(JNIEnv *env) {
    JavaVM *vm;
    (*env)->GetJavaVM(env, &vm);
    return vm;
}

static JNIEnv* getEnv(JavaVM *vm) {
    JNIEnv *env;
    if ((*vm)->GetEnv(vm, (void**)&env, JNI_VERSION_1_6) != JNI_OK) {
        return NULL;
    }
    return env;
}

static JNIEnv* attachCurrentThread(JavaVM *vm) {
    JNIEnv *env;
    (*vm)->AttachCurrentThread(vm, &env, NULL);
    return env;
}

static void detachCurrentThread(JavaVM *vm) {
    (*vm)->DetachCurrentThread(vm);
}

static jboolean isNull(jobject obj) {
    return obj == NULL;
}

static jboolean isMethodNull(jmethodID method) {
    return method == NULL;
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt32 GoInt;
typedef GoUint32 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_32_bit_pointer_matching_GoInt[sizeof(void*)==32/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern jstring Java_com_aegisnet_singbox_SingBoxController_startSingBox(JNIEnv* env, jclass clazz, jstring configJson, jint fd);
extern void Java_com_aegisnet_singbox_SingBoxController_stopSingBox(JNIEnv* env, jclass clazz);
extern jlongArray Java_com_aegisnet_singbox_SingBoxController_getTrafficStats(JNIEnv* env, jclass clazz);
extern jlong Java_com_aegisnet_singbox_SingBoxController_getBlockedCount(JNIEnv* env, jclass clazz);

#ifdef __cplusplus
}
#endif
