package com.aegisnet.singbox

import com.aegisnet.vpn.AegisVpnService
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class SingBoxController @Inject constructor() {

    init {
        // Load the cross-compiled C-Shared JNI library generated by our Go build script
        // from the `core/singbox-jni/main.go` source mapping to prebuilt/<arch>/libsingbox.so
        System.loadLibrary("singbox")
    }

    private var vpnService: AegisVpnService? = null

    fun setVpnService(service: AegisVpnService) {
        this.vpnService = service
    }

    /**
     * Called by JNI (Go) to protect a socket from being routed through the VPN.
     */
    fun protect(fd: Int): Boolean {
        return vpnService?.protect(fd) ?: false
    }

    /**
     * Bootstraps the sing-box instance globally.
     * @param configJson String-ified dynamic JSON resolving Rules and Outbounds.
     * @param fd the active VpnService intercept TUN descriptor index.
     * @return empty string if successful, else crash stacktrace.
     */
    external fun startSingBox(configJson: String, fd: Int): String

    /**
     * Gracefully halts networking listeners terminating the Go routine memory loop.
     */
    external fun stopSingBox()

    /**
     * Returns the total traffic statistics since the engine started.
     * @return Array containing [txBytes, rxBytes]
     */
    external fun getTrafficStats(): LongArray

    /**
     * Returns the number of blocked requests since the engine started.
     */
    external fun getBlockedCount(): Long
}
